server:
  port: 10088
spring:
  application:
    name: zuul #指定服务名
eureka:
  client:
    service-url: #指定Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:10086/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    fs:
      path: /fs/** #配置请求的URL的请求规则
      serviceId: fs #指定Eureka注册中心中的服务id
