server:
  port: 8081
spring:
  application:
    name: user
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/scf?characterEncoding=UTF8
    username: root
    password: 1
  jpa:
    database: MySQL
    show-sql: true
#  data:
#    elasticsearch:
#      cluster-nodes: 127.0.0.1:9300
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
    static-path-pattern: static/**
eureka:
  client:
    service-url: #指定Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:10086/eureka/
  instance:
    prefer-ip-address: true
jwt:
  config:
    key: bawei